rds_instance_id: 
db_subnet_group_name: 
s3_bucket: 
aws_access_key_id: 
aws_secret_access_key: 
mysql_database: 
mysql_username: 
mysql_password: 
dump_ttl: 0
data_dog_api_key: 
obfuscate_sql: test_data/obfuscate.sql
dump_directory: test_output